### ISSUE TITLE
동료들이 고른 나의 이미지 태그

### ISSUE THREAD

**Issue by oyeon-kwon** [depromeet/na-lab-client#145]
## 설명
<img width="785" alt="스크린샷 2023-05-24 오후 1 59 39" src="https://github.com/depromeet/na-lab-client/assets/61301574/88c27ab3-7333-4956-9ef1-0fc31186dc0f">

* Large / Small 사이즈 구분 필요

**Comment by hyesungoh** [comment]
#139 와 같이 다루면 좋을 거 같은데,

혹시 크기나 radius나 ...  스타일이 다를까요??

**Comment by oyeon-kwon** [comment]
오 아니요 크기는 같은 것 같은데 내부 아이콘이 달라서 만들려고 했었어요! 같은 컴포넌트로 아이콘 다르게 사용 가능하다면, 139 랑 같이 다루면 좋겠습니다~!

**Comment by hyesungoh** [comment]
같이 다룰 수 있도록 만들어 보겠습니다 ~~

**Comment by oyeon-kwon** [comment]
혜성님이 더 작업 할게 많으실텐데.. 제가 할까요?!

> 저도 내일..쯤 완성될 것 같긴 합니다..~

**Comment by oyeon-kwon** [comment]
엇 아니네 보니까 뒤에 숫자도 있긴해서.. 따로만들어야 하나 고민되네요..
<img width="59" alt="스크린샷 2023-05-24 오후 4 13 09" src="https://github.com/depromeet/na-lab-client/assets/61301574/1ab27894-f646-4661-bf5f-e1dc0f12c21f">
