### ISSUE TITLE
DND 라이브러리 추가 및 교체

### ISSUE THREAD

**Issue by sumi-0011** [depromeet/na-lab-client#214]
## 설명
기존에 사용하던 framer motion 라이브러리의 dnd 기능의 한계를 느껴 DND 라이브러리를 사용하려고 합니다.
`react-beautiful-dnd` 라이브러리를 사용해서 기존 코드를 교체하겠습니다. 

### As is
- framer motion reorder 기능 사용해서 dnd 구현
### To be
- `react-beautiful-dnd` 라이브러리 이용해 dnd 구현

## 할 일

- [ ] `react-beautiful-dnd` 라이브러리 적용
- [ ] DND 구현
- [ ] DND 애니매이션 구현
- [ ] 쓰레기통에 drop해 삭제하는 기능 추가

**Comment by hyesungoh** [comment]
번들링 사이즈는 얼마나되나요??

어떤 점에서 한계를 느끼셨는지, 새로 도입할 라이브러리는 어떻게 제공하는지 공유해 주시면 좋을 거 같아요!

**Comment by sumi-0011** [comment]
## 번들링 사이즈
npm 사이트 : https://www.npmjs.com/package/react-beautiful-dnd
<img width="403" alt="image" src="https://github.com/depromeet/na-lab-client/assets/49177223/d92bbf35-e77f-4dc6-976f-8e6b61feed77">

**Comment by sumi-0011** [comment]
처음에는 framer motion의 reorder을 사용해서 구현하였고, 질문 아이템을 drag and drop 하는 기능은 구현하였습니다.
그런데 아이템을 빠져나가면 `onPointerUp`과 같은 이벤트가 발생하지 않아, 질문이 삭제되지 않는 등 예기치 않은 문제가 발생하였습니다. 

drag를 하는 동안만 쓰레기통을 표시하는 요구사항은 구현이 가능했지만, 쓰레기통 위에 아이템을 올리는 것을 감지하는 부분이 구현이 어려웠습니다. 
> 그리고 `질문을 드래그해서 쓰레기통에 가까워 지면 점점 작아지는 기능`을 구현하기 위해 scroll을 계속 탐지하는 방법을 사용해서 리소스가 많이 들것 같다는 생각이 들었습니다. 

`쓰레기통에 가까워지면 점점 작아지는 기능`이 필요한 이유가 삭제가 가능함을 알려주기 위해서라고 생각해서 
디자이너분들에게 `쓰레기통에 가까워지면 점점 작아진다`가 아닌 `쓰레기통에 올리면 쓰레기통 뚜껑이 열린다`라는 기능으로 바꾸면 어떨지 여쭤보고, 
쓰레기통 뚜껑이 열리는 기능으로 하기로 결정하였습니다. 

쓰레기통에 올리면 쓰레기통 뚜껑이 열리는 기능을 구현하려고 하면 
- 쓰레기통 위에 질문을 올렸을 때 `drop over`등의 이벤트가 발생해야하는데, 
- 이 이벤트가 발생하려면 질문이 drag가 가능한 요소여야한다는 제약이 있고
- 질문 컴포넌트에 `draggable=true`속성을 주면 drag 가능한 요소가 되지만, 
- `draggable=true` 속성을 추가하는 순간 에러가 발생해서 포기?했습니다.
```
helpers.js:112 Uncaught TypeError: Cannot destructure property 'velocity' of 'gesturePoint' as it is undefined.
```

그래서 결국 framer motion 사용해서 쓰레기통 기능을 구현하는건 어렵겠다는 결론을 내렸죠!
상조님이 전에 칸반보드 만드시면서 사용한 `react-beautiful-dnd` 라이브러리를 추천해주셔서, 그거로 교체할 생각이였습니다.
