### ISSUE TITLE
질문 추가 form 틀 컴포넌트 제작

### ISSUE THREAD

**Issue by sumi-0011** [depromeet/na-lab-client#56]
## 설명
질문 추가 form 틀 컴포넌트 제작
![image](https://github.com/depromeet/na-lab-client/assets/49177223/abd316f0-b054-46e7-a604-d4fe2e1976c0)

## 할 일

- [ ] 객관식, 주관식 상태 추가

**Comment by hyesungoh** [comment]
`bottom sheet는 full + 둥근 모서리` 부분 잘못 누르고 이슈로 만들어버렸네요 ㅋㅋㅋㅋ

바텀 시트 관련 부분은 행위가 분산되는 거 같아 따로 핸들링하는게 나을 거 같아요 ~

**Comment by sumi-0011** [comment]
> `bottom sheet는 full + 둥근 모서리` 부분 잘못 누르고 이슈로 만들어버렸네요 ㅋㅋㅋㅋ
> 
> 바텀 시트 관련 부분은 행위가 분산되는 거 같아 따로 핸들링하는게 나을 거 같아요 ~

따로 이슈를 만드는게 좋겠다는 말씀이신거죠?! 
제가 같이 수정해보겠습니당

**Comment by hyesungoh** [comment]
@sumi-0011 

네넵 ! 정확히는 PR을 분리하는 것...이랄까요 ?! 

본 이슈에서는 바텀 시트를 사용만하고, 바텀 시트 스타일은 확정되면 핸들링하는게 좋다고 느껴져서요!! 

물론 수미님이 같이 하시는게 좋다고 생각되신다면 그렇게 하셔도 좋아요 ~~~ 👍 💯
